Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,4 +30,4 @@ jobs:
           echo "PR labels : $OP_TEST_LABELS"
           echo "repo name: ${{ github.event.pull_request.head.repo.full_name }}"
           yq --version
-          [ command -v yq &> /dev/null ] || { echo "Command 'yq' could not be found !!!"; exit 1; } 
+          [ yq --version &> /dev/null ] || { echo "Command 'yq' could not be found !!!"; exit 1; } 
