Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,7 @@ jobs:
         with:
           python-version: '3.x'
       - name: Install dependencies
-        run: python -m pip install --upgrade pip setuptools yq
+        run: python -m pip install --upgrade pip yq
 
       - name: Main
         id: main
@@ -30,3 +30,4 @@ jobs:
           echo "PR labels : $OP_TEST_LABELS"
           echo "repo name: ${{ github.event.pull_request.head.repo.full_name }}"
           yq --version
+          [ command -v yq &> /dev/null ] || { echo "Command 'yq' could not be found !!!"; exit 1; } 
